import mongoose from "mongoose";
import dotenv from "dotenv";
import User from "../models/User.js";
import Product from "../models/Product.js";
import { Category } from "../models/Review.js";
import Order from "../models/Order.js";

dotenv.config();
const categories = [
  { name: "Electronics", icon: "📱", gradient: "from-blue-500 to-blue-700" },
  { name: "Fashion", icon: "👗", gradient: "from-pink-500 to-pink-700" },
  {
    name: "Home & Furniture",
    icon: "🛋️",
    gradient: "from-yellow-500 to-orange-600",
  },
  { name: "Appliances", icon: "🏠", gradient: "from-green-500 to-green-700" },
  { name: "Beauty", icon: "💄", gradient: "from-purple-500 to-purple-700" },
  { name: "Sports", icon: "⚽", gradient: "from-red-500 to-red-700" },
  { name: "Books", icon: "📚", gradient: "from-indigo-500 to-indigo-700" },
  { name: "Toys", icon: "🧸", gradient: "from-orange-400 to-orange-600" },
  { name: "Grocery", icon: "🛒", gradient: "from-teal-500 to-teal-700" },
];
const products = [
  // Electronics
  {
    name: "Apple iPhone 15 128GB",
    brand: "Apple",
    category: "Electronics",
    price: 74999,
    originalPrice: 79999,
    discount: 6,
    stock: 120,
    rating: 4.7,
    numReviews: 15000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Latest Apple iPhone with A16 Bionic chip and advanced camera system.",
    highlights: ["128GB Storage", "48MP Camera", "iOS 17"],
    image: "/images/products/iphone15.jpg",
    images: ["/images/products/iphone15.jpg"],
    tags: ["iphone", "apple", "mobile"],
    seller: "Apple Store",
    warranty: "1 Year",
  },
  {
    name: "Samsung Galaxy S23 256GB",
    brand: "Samsung",
    category: "Electronics",
    price: 64999,
    originalPrice: 74999,
    discount: 13,
    stock: 90,
    rating: 4.5,
    numReviews: 9800,
    badge: "Top Rated",
    isFeatured: true,
    description: "Samsung Galaxy S23 with Snapdragon 8 Gen 2 and 200MP camera.",
    highlights: ["256GB Storage", "200MP Camera", "5000mAh Battery"],
    image: "/images/products/samsung-s23.jpg",
    images: ["/images/products/samsung-s23.jpg"],
    tags: ["samsung", "galaxy", "mobile"],
    seller: "Samsung Store",
    warranty: "1 Year",
  },
  {
    name: "HP Laptop 15s Intel i5",
    brand: "HP",
    category: "Electronics",
    price: 52999,
    originalPrice: 62999,
    discount: 16,
    stock: 60,
    rating: 4.3,
    numReviews: 5400,
    badge: "Popular",
    isFeatured: false,
    description: "HP 15s laptop with Intel i5 12th Gen, 8GB RAM and 512GB SSD.",
    highlights: ["Intel i5 12th Gen", "8GB RAM", "512GB SSD"],
    image: "/images/products/hp-laptop.jpg",
    images: ["/images/products/hp-laptop.jpg"],
    tags: ["hp", "laptop", "computer"],
    seller: "HP World",
    warranty: "1 Year",
  },
  {
    name: "boAt Rockerz 450 Bluetooth Headphones",
    brand: "boAt",
    category: "Electronics",
    price: 1299,
    originalPrice: 2990,
    discount: 57,
    stock: 200,
    rating: 4.2,
    numReviews: 32000,
    badge: "Best Seller",
    isFeatured: true,
    description: "boAt Rockerz 450 wireless headphones with 15 hours playback and deep bass.",
    highlights: ["15Hr Playback", "40mm Drivers", "Foldable Design"],
    image: "/images/products/boat-headphones.jpg",
    images: ["/images/products/boat-headphones.jpg"],
    tags: ["boat", "headphones", "wireless"],
    seller: "boAt Official",
    warranty: "1 Year",
  },
  {
    name: "Apple iPad 10th Gen 64GB",
    brand: "Apple",
    category: "Electronics",
    price: 44900,
    originalPrice: 49900,
    discount: 10,
    stock: 75,
    rating: 4.6,
    numReviews: 7200,
    badge: "New Launch",
    isFeatured: true,
    description: "Apple iPad 10th Gen with A14 Bionic chip and 10.9 inch Liquid Retina display.",
    highlights: ["10.9 inch Display", "A14 Bionic", "64GB Storage"],
    image: "/images/products/ipad.jpg",
    images: ["/images/products/ipad.jpg"],
    tags: ["ipad", "apple", "tablet"],
    seller: "Apple Store",
    warranty: "1 Year",
  },
  {
    name: "OnePlus Nord CE 3 Lite",
    brand: "OnePlus",
    category: "Electronics",
    price: 19999,
    originalPrice: 24999,
    discount: 20,
    stock: 150,
    rating: 4.1,
    numReviews: 11200,
    badge: "Value Pick",
    isFeatured: false,
    description: "OnePlus Nord CE 3 Lite with Snapdragon 695 and 108MP camera.",
    highlights: ["108MP Camera", "5000mAh Battery", "67W Fast Charging"],
    image: "/images/products/oneplus-nord.jpg",
    images: ["/images/products/oneplus-nord.jpg"],
    tags: ["oneplus", "nord", "mobile"],
    seller: "OnePlus Store",
    warranty: "1 Year",
  },
  {
    name: "Canon EOS 1500D DSLR Camera",
    brand: "Canon",
    category: "Electronics",
    price: 34995,
    originalPrice: 42000,
    discount: 17,
    stock: 40,
    rating: 4.5,
    numReviews: 4300,
    badge: "Top Rated",
    isFeatured: true,
    description: "Canon EOS 1500D with 24.1MP sensor and Full HD video recording.",
    highlights: ["24.1MP Sensor", "Full HD Video", "Wi-Fi Enabled"],
    image: "/images/products/canon-camera.jpg",
    images: ["/images/products/canon-camera.jpg"],
    tags: ["canon", "camera", "dslr"],
    seller: "Canon India",
    warranty: "2 Years",
  },
  {
    name: "Dell 27 inch FHD Monitor",
    brand: "Dell",
    category: "Electronics",
    price: 18999,
    originalPrice: 22999,
    discount: 17,
    stock: 55,
    rating: 4.4,
    numReviews: 3100,
    badge: "Popular",
    isFeatured: false,
    description: "Dell 27 inch Full HD IPS monitor with ultra-thin bezels and HDMI port.",
    highlights: ["27 inch FHD", "IPS Panel", "75Hz Refresh Rate"],
    image: "/images/products/dell-monitor.jpg",
    images: ["/images/products/dell-monitor.jpg"],
    tags: ["dell", "monitor", "display"],
    seller: "Dell Store",
    warranty: "3 Years",
  },
  {
    name: "Sony Bravia 43 inch 4K TV",
    brand: "Sony",
    category: "Electronics",
    price: 49990,
    originalPrice: 59990,
    discount: 17,
    stock: 35,
    rating: 4.6,
    numReviews: 8700,
    badge: "Best Seller",
    isFeatured: true,
    description: "Sony Bravia 43 inch 4K Ultra HD Smart LED TV with Google TV.",
    highlights: ["4K Ultra HD", "Google TV", "Dolby Audio"],
    image: "/images/products/sony-tv.jpg",
    images: ["/images/products/sony-tv.jpg"],
    tags: ["sony", "tv", "television"],
    seller: "Sony India",
    warranty: "1 Year",
  },
  // Fashion
  {
    name: "Levi's 511 Slim Fit Jeans",
    brand: "Levi's",
    category: "Fashion",
    price: 1899,
    originalPrice: 3999,
    discount: 48,
    stock: 180,
    rating: 4.4,
    numReviews: 21000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Levi's 511 slim fit jeans made from stretch denim for all-day comfort.",
    highlights: ["Slim Fit", "Stretch Denim", "5-Pocket Style"],
    image: "/images/products/levis-jeans.jpg",
    images: ["/images/products/levis-jeans.jpg"],
    tags: ["levis", "jeans", "fashion"],
    seller: "Levi's India",
    warranty: "",
  },
  {
    name: "Puma Men's Dry Cell T-Shirt",
    brand: "Puma",
    category: "Fashion",
    price: 799,
    originalPrice: 1499,
    discount: 47,
    stock: 250,
    rating: 4.2,
    numReviews: 14500,
    badge: "Popular",
    isFeatured: false,
    description: "Puma Dry Cell T-Shirt with moisture-wicking technology for active wear.",
    highlights: ["Dry Cell Technology", "100% Polyester", "Regular Fit"],
    image: "/images/products/puma-tshirt.jpg",
    images: ["/images/products/puma-tshirt.jpg"],
    tags: ["puma", "tshirt", "fashion"],
    seller: "Puma Store",
    warranty: "",
  },
  {
    name: "Nike Air Max 270 Running Shoes",
    brand: "Nike",
    category: "Fashion",
    price: 8995,
    originalPrice: 11995,
    discount: 25,
    stock: 100,
    rating: 4.5,
    numReviews: 9200,
    badge: "Top Rated",
    isFeatured: true,
    description: "Nike Air Max 270 with large Air unit for all-day comfort and style.",
    highlights: ["Air Max Cushioning", "Mesh Upper", "Rubber Outsole"],
    image: "/images/products/nike-airmax.jpg",
    images: ["/images/products/nike-airmax.jpg"],
    tags: ["nike", "shoes", "airmax"],
    seller: "Nike India",
    warranty: "",
  },
  {
    name: "Biba Women's Straight Kurti",
    brand: "Biba",
    category: "Fashion",
    price: 1299,
    originalPrice: 2199,
    discount: 41,
    stock: 130,
    rating: 4.3,
    numReviews: 6700,
    badge: "Trending",
    isFeatured: false,
    description: "Biba straight kurti in cotton fabric with beautiful ethnic print.",
    highlights: ["100% Cotton", "Ethnic Print", "Straight Fit"],
    image: "/images/products/biba-kurti.jpg",
    images: ["/images/products/biba-kurti.jpg"],
    tags: ["biba", "kurti", "ethnic"],
    seller: "Biba Fashion",
    warranty: "",
  },
  {
    name: "Fossil Men's Analog Watch",
    brand: "Fossil",
    category: "Fashion",
    price: 6995,
    originalPrice: 9995,
    discount: 30,
    stock: 80,
    rating: 4.5,
    numReviews: 5100,
    badge: "Premium",
    isFeatured: true,
    description: "Fossil men's analog watch with stainless steel case and leather strap.",
    highlights: ["Stainless Steel Case", "Leather Strap", "Water Resistant"],
    image: "/images/products/watch.jpg",
    images: ["/images/products/watch.jpg"],
    tags: ["fossil", "watch", "fashion"],
    seller: "Fossil Store",
    warranty: "2 Years",
  },
  // Home & Furniture
  {
    name: "Wakefit Orthopedic Memory Foam Mattress",
    brand: "Wakefit",
    category: "Home & Furniture",
    price: 12999,
    originalPrice: 18999,
    discount: 32,
    stock: 45,
    rating: 4.5,
    numReviews: 18000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Wakefit orthopedic memory foam mattress for superior back support and comfort.",
    highlights: ["Memory Foam", "Orthopedic Support", "5 Year Warranty"],
    image: "/images/products/mattress.jpg",
    images: ["/images/products/mattress.jpg"],
    tags: ["mattress", "wakefit", "furniture"],
    seller: "Wakefit",
    warranty: "5 Years",
  },
  {
    name: "Nilkamal 3 Seater Sofa",
    brand: "Nilkamal",
    category: "Home & Furniture",
    price: 18999,
    originalPrice: 25999,
    discount: 27,
    stock: 20,
    rating: 4.2,
    numReviews: 3200,
    badge: "Popular",
    isFeatured: false,
    description: "Nilkamal 3 seater sofa with premium fabric upholstery and solid wood legs.",
    highlights: ["Premium Fabric", "Solid Wood Legs", "Easy Assembly"],
    image: "/images/products/sofa.jpg",
    images: ["/images/products/sofa.jpg"],
    tags: ["sofa", "nilkamal", "furniture"],
    seller: "Nilkamal Furniture",
    warranty: "1 Year",
  },
  {
    name: "Spacewood Study Table with Bookshelf",
    brand: "Spacewood",
    category: "Home & Furniture",
    price: 7499,
    originalPrice: 10999,
    discount: 32,
    stock: 60,
    rating: 4.3,
    numReviews: 4100,
    badge: "Trending",
    isFeatured: false,
    description: "Spacewood study table with attached bookshelf and drawer storage.",
    highlights: ["Bookshelf Attached", "Drawer Storage", "Engineered Wood"],
    image: "/images/products/study-table.jpg",
    images: ["/images/products/study-table.jpg"],
    tags: ["study table", "furniture", "spacewood"],
    seller: "Spacewood",
    warranty: "1 Year",
  },
  // Appliances
  {
    name: "LG 260L Double Door Refrigerator",
    brand: "LG",
    category: "Appliances",
    price: 28990,
    originalPrice: 35990,
    discount: 19,
    stock: 30,
    rating: 4.4,
    numReviews: 7600,
    badge: "Top Rated",
    isFeatured: true,
    description: "LG 260L frost-free double door refrigerator with smart inverter compressor.",
    highlights: ["260L Capacity", "Frost Free", "Smart Inverter"],
    image: "/images/products/refrigerator.jpg",
    images: ["/images/products/refrigerator.jpg"],
    tags: ["lg", "refrigerator", "appliance"],
    seller: "LG Electronics",
    warranty: "1 Year",
  },
  {
    name: "IFB 6.5kg Fully Automatic Washing Machine",
    brand: "IFB",
    category: "Appliances",
    price: 22990,
    originalPrice: 29990,
    discount: 23,
    stock: 25,
    rating: 4.3,
    numReviews: 5400,
    badge: "Popular",
    isFeatured: false,
    description: "IFB 6.5kg front load fully automatic washing machine with steam wash.",
    highlights: ["6.5kg Capacity", "Steam Wash", "1200 RPM"],
    image: "/images/products/washing-machine.jpg",
    images: ["/images/products/washing-machine.jpg"],
    tags: ["ifb", "washing machine", "appliance"],
    seller: "IFB Store",
    warranty: "2 Years",
  },
  {
    name: "Philips HL7756 Mixer Grinder 750W",
    brand: "Philips",
    category: "Appliances",
    price: 2799,
    originalPrice: 4499,
    discount: 38,
    stock: 110,
    rating: 4.4,
    numReviews: 22000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Philips 750W mixer grinder with 3 jars and turbo clean technology.",
    highlights: ["750W Motor", "3 Jars", "Turbo Clean"],
    image: "/images/products/mixer-grinder.jpg",
    images: ["/images/products/mixer-grinder.jpg"],
    tags: ["philips", "mixer", "appliance"],
    seller: "Philips India",
    warranty: "2 Years",
  },
  // Beauty
  {
    name: "Lakme Absolute Skin Natural Mousse Foundation",
    brand: "Lakme",
    category: "Beauty",
    price: 449,
    originalPrice: 699,
    discount: 36,
    stock: 200,
    rating: 4.1,
    numReviews: 13500,
    badge: "Popular",
    isFeatured: false,
    description: "Lakme Absolute mousse foundation with SPF 8 for natural skin finish.",
    highlights: ["SPF 8", "Mousse Texture", "Natural Finish"],
    image: "/images/products/foundation.jpg",
    images: ["/images/products/foundation.jpg"],
    tags: ["lakme", "foundation", "beauty"],
    seller: "Lakme Beauty",
    warranty: "",
  },
  {
    name: "Mamaearth Onion Hair Oil 250ml",
    brand: "Mamaearth",
    category: "Beauty",
    price: 349,
    originalPrice: 499,
    discount: 30,
    stock: 300,
    rating: 4.3,
    numReviews: 28000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Mamaearth onion hair oil with redensyl for hair fall control and growth.",
    highlights: ["Onion Extract", "Redensyl", "Toxin Free"],
    image: "/images/products/hair-oil.jpg",
    images: ["/images/products/hair-oil.jpg"],
    tags: ["mamaearth", "hair oil", "beauty"],
    seller: "Mamaearth",
    warranty: "",
  },
  // Sports
  {
    name: "Yonex GR 303 Badminton Racket",
    brand: "Yonex",
    category: "Sports",
    price: 599,
    originalPrice: 899,
    discount: 33,
    stock: 160,
    rating: 4.2,
    numReviews: 9800,
    badge: "Popular",
    isFeatured: false,
    description: "Yonex GR 303 aluminum badminton racket for beginners and intermediate players.",
    highlights: ["Aluminum Frame", "Full Cover Included", "Isometric Head Shape"],
    image: "/images/products/badminton.jpg",
    images: ["/images/products/badminton.jpg"],
    tags: ["yonex", "badminton", "sports"],
    seller: "Yonex Sports",
    warranty: "",
  },
  {
    name: "Nivia Storm Football Size 5",
    brand: "Nivia",
    category: "Sports",
    price: 699,
    originalPrice: 999,
    discount: 30,
    stock: 140,
    rating: 4.1,
    numReviews: 6200,
    badge: "Trending",
    isFeatured: false,
    description: "Nivia Storm football size 5 with machine stitched panels for durability.",
    highlights: ["Size 5", "Machine Stitched", "PVC Material"],
    image: "/images/products/football.jpg",
    images: ["/images/products/football.jpg"],
    tags: ["nivia", "football", "sports"],
    seller: "Nivia Sports",
    warranty: "",
  },
  {
    name: "Cosco Skipping Rope",
    brand: "Cosco",
    category: "Sports",
    price: 199,
    originalPrice: 349,
    discount: 43,
    stock: 300,
    rating: 4.0,
    numReviews: 8100,
    badge: "Value Pick",
    isFeatured: false,
    description: "Cosco skipping rope with comfortable foam handles for cardio workouts.",
    highlights: ["Foam Handles", "Adjustable Length", "Lightweight"],
    image: "/images/products/skipping-rope.jpg",
    images: ["/images/products/skipping-rope.jpg"],
    tags: ["cosco", "skipping rope", "sports"],
    seller: "Cosco Sports",
    warranty: "",
  },
  {
    name: "Adidas Ultraboost Running Shoes",
    brand: "Adidas",
    category: "Sports",
    price: 7999,
    originalPrice: 10999,
    discount: 27,
    stock: 85,
    rating: 4.5,
    numReviews: 7400,
    badge: "Top Rated",
    isFeatured: true,
    description: "Adidas Ultraboost running shoes with Boost midsole for energy return.",
    highlights: ["Boost Midsole", "Primeknit Upper", "Continental Rubber Outsole"],
    image: "/images/products/adidas-shoes.jpg",
    images: ["/images/products/adidas-shoes.jpg"],
    tags: ["adidas", "shoes", "running"],
    seller: "Adidas India",
    warranty: "",
  },
  // Books
  {
    name: "Atomic Habits by James Clear",
    brand: "Penguin",
    category: "Books",
    price: 399,
    originalPrice: 599,
    discount: 33,
    stock: 500,
    rating: 4.8,
    numReviews: 45000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Atomic Habits by James Clear — a proven framework for building good habits.",
    highlights: ["Paperback", "English", "320 Pages"],
    image: "/images/products/atomic-habits.jpg",
    images: ["/images/products/atomic-habits.jpg"],
    tags: ["books", "self help", "habits"],
    seller: "Penguin Books",
    warranty: "",
  },
  {
    name: "Rich Dad Poor Dad by Robert Kiyosaki",
    brand: "Manjul Publishing",
    category: "Books",
    price: 299,
    originalPrice: 450,
    discount: 34,
    stock: 400,
    rating: 4.7,
    numReviews: 38000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Rich Dad Poor Dad — the #1 personal finance book of all time by Robert Kiyosaki.",
    highlights: ["Paperback", "English", "336 Pages"],
    image: "/images/products/rich-dad.jpg",
    images: ["/images/products/rich-dad.jpg"],
    tags: ["books", "finance", "self help"],
    seller: "Manjul Publishing",
    warranty: "",
  },
  {
    name: "Ikigai by Hector Garcia",
    brand: "Penguin",
    category: "Books",
    price: 249,
    originalPrice: 399,
    discount: 38,
    stock: 350,
    rating: 4.6,
    numReviews: 29000,
    badge: "Popular",
    isFeatured: false,
    description: "Ikigai — the Japanese secret to a long and happy life by Hector Garcia.",
    highlights: ["Paperback", "English", "208 Pages"],
    image: "/images/products/ikigai.jpg",
    images: ["/images/products/ikigai.jpg"],
    tags: ["books", "ikigai", "self help"],
    seller: "Penguin Books",
    warranty: "",
  },
  // Toys
  {
    name: "LEGO Classic Creative Bricks Set",
    brand: "LEGO",
    category: "Toys",
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    stock: 120,
    rating: 4.7,
    numReviews: 12000,
    badge: "Best Seller",
    isFeatured: true,
    description: "LEGO Classic Creative Bricks set with 484 pieces for endless building fun.",
    highlights: ["484 Pieces", "Age 4+", "Multiple Colors"],
    image: "/images/products/lego.jpg",
    images: ["/images/products/lego.jpg"],
    tags: ["lego", "toys", "building blocks"],
    seller: "LEGO Store",
    warranty: "",
  },
  {
    name: "Barbie Dreamhouse Playset",
    brand: "Barbie",
    category: "Toys",
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    stock: 60,
    rating: 4.5,
    numReviews: 8700,
    badge: "Popular",
    isFeatured: false,
    description: "Barbie Dreamhouse playset with 3 floors, 8 rooms and 70+ accessories.",
    highlights: ["3 Floors", "8 Rooms", "70+ Accessories"],
    image: "/images/products/barbie.jpg",
    images: ["/images/products/barbie.jpg"],
    tags: ["barbie", "toys", "girls"],
    seller: "Mattel India",
    warranty: "",
  },
  // Grocery
  {
    name: "Tata Salt 1kg",
    brand: "Tata",
    category: "Grocery",
    price: 28,
    originalPrice: 32,
    discount: 13,
    stock: 1000,
    rating: 4.6,
    numReviews: 52000,
    badge: "Daily Essential",
    isFeatured: false,
    description: "Tata Salt vacuum evaporated iodized salt for healthy cooking.",
    highlights: ["Iodized Salt", "1kg Pack", "Vacuum Evaporated"],
    image: "/images/products/tata-salt.jpg",
    images: ["/images/products/tata-salt.jpg"],
    tags: ["tata", "salt", "grocery"],
    seller: "Tata Consumer",
    warranty: "",
  },
  {
    name: "Aashirvaad Whole Wheat Atta 5kg",
    brand: "Aashirvaad",
    category: "Grocery",
    price: 249,
    originalPrice: 299,
    discount: 17,
    stock: 800,
    rating: 4.5,
    numReviews: 41000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Aashirvaad whole wheat atta made from 100% whole wheat for soft rotis.",
    highlights: ["100% Whole Wheat", "5kg Pack", "High Fibre"],
    image: "/images/products/atta.jpg",
    images: ["/images/products/atta.jpg"],
    tags: ["aashirvaad", "atta", "grocery"],
    seller: "ITC Foods",
    warranty: "",
  },
  // Grocery
  {
    name: "Maggi 2-Minute Noodles 12 Pack",
    brand: "Maggi",
    category: "Grocery",
    price: 144,
    originalPrice: 168,
    discount: 14,
    stock: 900,
    rating: 4.5,
    numReviews: 63000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Maggi 2-Minute Masala Noodles pack of 12 for quick and tasty meals.",
    highlights: ["Pack of 12", "2 Minute Cook", "Masala Flavour"],
    image: "/images/products/maggi.jpg",
    images: ["/images/products/maggi.jpg"],
    tags: ["maggi", "noodles", "grocery"],
    seller: "Nestle India",
    warranty: "",
  },
  {
    name: "Tata Tea Gold 500g",
    brand: "Tata Tea",
    category: "Grocery",
    price: 249,
    originalPrice: 290,
    discount: 14,
    stock: 700,
    rating: 4.4,
    numReviews: 34000,
    badge: "Popular",
    isFeatured: false,
    description: "Tata Tea Gold 500g with rich aroma and full-bodied taste.",
    highlights: ["500g Pack", "Rich Aroma", "Full Bodied"],
    image: "/images/products/tata-tea.jpg",
    images: ["/images/products/tata-tea.jpg"],
    tags: ["tata tea", "tea", "grocery"],
    seller: "Tata Consumer",
    warranty: "",
  },
  {
    name: "Fortune Sunflower Oil 5L",
    brand: "Fortune",
    category: "Grocery",
    price: 699,
    originalPrice: 850,
    discount: 18,
    stock: 500,
    rating: 4.3,
    numReviews: 21000,
    badge: "Value Pack",
    isFeatured: false,
    description: "Fortune sunflower oil 5L with light taste and high smoke point for cooking.",
    highlights: ["5L Pack", "Light Taste", "High Smoke Point"],
    image: "/images/products/sunflower-oil.jpg",
    images: ["/images/products/sunflower-oil.jpg"],
    tags: ["fortune", "oil", "grocery"],
    seller: "Adani Wilmar",
    warranty: "",
  },
  {
    name: "Britannia Good Day Butter Cookies 1kg",
    brand: "Britannia",
    category: "Grocery",
    price: 199,
    originalPrice: 240,
    discount: 17,
    stock: 600,
    rating: 4.4,
    numReviews: 18000,
    badge: "Popular",
    isFeatured: false,
    description: "Britannia Good Day butter cookies 1kg family pack with rich buttery taste.",
    highlights: ["1kg Pack", "Butter Flavour", "Crispy Texture"],
    image: "/images/products/britannia.jpg",
    images: ["/images/products/britannia.jpg"],
    tags: ["britannia", "cookies", "grocery"],
    seller: "Britannia Industries",
    warranty: "",
  },
  // Appliances
  {
    name: "LG 32 inch HD Smart TV",
    brand: "LG",
    category: "Appliances",
    price: 17990,
    originalPrice: 22990,
    discount: 22,
    stock: 50,
    rating: 4.3,
    numReviews: 9100,
    badge: "Popular",
    isFeatured: false,
    description: "LG 32 inch HD Smart TV with WebOS and built-in Wi-Fi.",
    highlights: ["32 inch HD", "WebOS", "Built-in Wi-Fi"],
    image: "/images/products/lg-tv.jpg",
    images: ["/images/products/lg-tv.jpg"],
    tags: ["lg", "tv", "appliance"],
    seller: "LG Electronics",
    warranty: "1 Year",
  },
  {
    name: "Samsung 25L Microwave Oven",
    brand: "Samsung",
    category: "Appliances",
    price: 8490,
    originalPrice: 11990,
    discount: 29,
    stock: 70,
    rating: 4.3,
    numReviews: 6700,
    badge: "Popular",
    isFeatured: false,
    description: "Samsung 25L solo microwave oven with ceramic enamel cavity and auto cook menu.",
    highlights: ["25L Capacity", "Ceramic Enamel", "Auto Cook Menu"],
    image: "/images/products/microwave.jpg",
    images: ["/images/products/microwave.jpg"],
    tags: ["samsung", "microwave", "appliance"],
    seller: "Samsung Store",
    warranty: "1 Year",
  },
  {
    name: "Havells Induction Cooktop 1900W",
    brand: "Havells",
    category: "Appliances",
    price: 1599,
    originalPrice: 2499,
    discount: 36,
    stock: 120,
    rating: 4.2,
    numReviews: 11200,
    badge: "Value Pick",
    isFeatured: false,
    description: "Havells 1900W induction cooktop with 7 preset menus and touch panel.",
    highlights: ["1900W Power", "7 Preset Menus", "Touch Panel"],
    image: "/images/products/induction.webp",
    images: ["/images/products/induction.webp"],
    tags: ["havells", "induction", "appliance"],
    seller: "Havells India",
    warranty: "2 Years",
  },
  // Beauty
  {
    name: "Neutrogena Sunscreen SPF 50 100ml",
    brand: "Neutrogena",
    category: "Beauty",
    price: 499,
    originalPrice: 699,
    discount: 29,
    stock: 250,
    rating: 4.4,
    numReviews: 17000,
    badge: "Top Rated",
    isFeatured: true,
    description: "Neutrogena Ultra Sheer sunscreen SPF 50 with Helioplex technology.",
    highlights: ["SPF 50", "Helioplex Tech", "Non-Greasy"],
    image: "/images/products/sunscreen.jpg",
    images: ["/images/products/sunscreen.jpg"],
    tags: ["neutrogena", "sunscreen", "beauty"],
    seller: "Neutrogena India",
    warranty: "",
  },
  {
    name: "Himalaya Purifying Neem Face Wash 150ml",
    brand: "Himalaya",
    category: "Beauty",
    price: 130,
    originalPrice: 175,
    discount: 26,
    stock: 400,
    rating: 4.3,
    numReviews: 42000,
    badge: "Best Seller",
    isFeatured: false,
    description: "Himalaya purifying neem face wash for oil control and pimple prevention.",
    highlights: ["Neem Extract", "Oil Control", "150ml"],
    image: "/images/products/face-wash.jpg",
    images: ["/images/products/face-wash.jpg"],
    tags: ["himalaya", "face wash", "beauty"],
    seller: "Himalaya Wellness",
    warranty: "",
  },
  {
    name: "Lakme Enrich Matte Lipstick",
    brand: "Lakme",
    category: "Beauty",
    price: 249,
    originalPrice: 375,
    discount: 34,
    stock: 300,
    rating: 4.2,
    numReviews: 19000,
    badge: "Trending",
    isFeatured: false,
    description: "Lakme Enrich Matte lipstick with rich colour payoff and long lasting formula.",
    highlights: ["Matte Finish", "Long Lasting", "Rich Colour"],
    image: "/images/products/lipstick.jpg",
    images: ["/images/products/lipstick.jpg"],
    tags: ["lakme", "lipstick", "beauty"],
    seller: "Lakme Beauty",
    warranty: "",
  },
  // Toys
  {
    name: "Hot Wheels 20 Car Gift Pack",
    brand: "Hot Wheels",
    category: "Toys",
    price: 999,
    originalPrice: 1499,
    discount: 33,
    stock: 150,
    rating: 4.6,
    numReviews: 14500,
    badge: "Best Seller",
    isFeatured: true,
    description: "Hot Wheels 20 car gift pack with die-cast metal cars in assorted styles.",
    highlights: ["20 Cars", "Die-Cast Metal", "Age 3+"],
    image: "/images/products/hot-wheels.jpg",
    images: ["/images/products/hot-wheels.jpg"],
    tags: ["hot wheels", "cars", "toys"],
    seller: "Mattel India",
    warranty: "",
  },
  {
    name: "Funskool Teddy Bear 30cm",
    brand: "Funskool",
    category: "Toys",
    price: 499,
    originalPrice: 799,
    discount: 38,
    stock: 200,
    rating: 4.4,
    numReviews: 7800,
    badge: "Popular",
    isFeatured: false,
    description: "Funskool soft and cuddly teddy bear 30cm made from premium plush fabric.",
    highlights: ["30cm Size", "Premium Plush", "Age 1+"],
    image: "/images/products/teddy-bear.jpg",
    images: ["/images/products/teddy-bear.jpg"],
    tags: ["teddy bear", "soft toy", "toys"],
    seller: "Funskool India",
    warranty: "",
  },
  {
    name: "Melissa & Doug Wooden Puzzle Set",
    brand: "Melissa & Doug",
    category: "Toys",
    price: 799,
    originalPrice: 1199,
    discount: 33,
    stock: 110,
    rating: 4.5,
    numReviews: 5600,
    badge: "Top Rated",
    isFeatured: false,
    description: "Melissa & Doug wooden puzzle set with 4 puzzles for early learning.",
    highlights: ["4 Puzzles", "Wooden Pieces", "Age 2+"],
    image: "/images/products/puzzle.jpg",
    images: ["/images/products/puzzle.jpg"],
    tags: ["puzzle", "wooden", "toys"],
    seller: "Melissa & Doug",
    warranty: "",
  },
  // Home & Furniture
  {
    name: "Godrej Interio Office Chair",
    brand: "Godrej",
    category: "Home & Furniture",
    price: 8999,
    originalPrice: 12999,
    discount: 31,
    stock: 40,
    rating: 4.3,
    numReviews: 4200,
    badge: "Popular",
    isFeatured: false,
    description: "Godrej Interio ergonomic office chair with lumbar support and adjustable height.",
    highlights: ["Lumbar Support", "Adjustable Height", "360° Swivel"],
    image: "/images/products/office-chair.jpg",
    images: ["/images/products/office-chair.jpg"],
    tags: ["godrej", "chair", "furniture"],
    seller: "Godrej Interio",
    warranty: "1 Year",
  },
  {
    name: "Durian Queen Size Bed with Storage",
    brand: "Durian",
    category: "Home & Furniture",
    price: 24999,
    originalPrice: 34999,
    discount: 29,
    stock: 15,
    rating: 4.4,
    numReviews: 2800,
    badge: "Premium",
    isFeatured: true,
    description: "Durian queen size bed with hydraulic storage and engineered wood frame.",
    highlights: ["Hydraulic Storage", "Queen Size", "Engineered Wood"],
    image: "/images/products/queen-bed.jpg",
    images: ["/images/products/queen-bed.jpg"],
    tags: ["bed", "durian", "furniture"],
    seller: "Durian Furniture",
    warranty: "2 Years",
  },
  {
    name: "Spacewood 3 Door Wardrobe",
    brand: "Spacewood",
    category: "Home & Furniture",
    price: 19999,
    originalPrice: 27999,
    discount: 29,
    stock: 25,
    rating: 4.2,
    numReviews: 3100,
    badge: "Popular",
    isFeatured: false,
    description: "Spacewood 3 door wardrobe with mirror and multiple shelves for storage.",
    highlights: ["3 Doors", "Mirror Included", "Multiple Shelves"],
    image: "/images/products/wardrobe.jpg",
    images: ["/images/products/wardrobe.jpg"],
    tags: ["wardrobe", "spacewood", "furniture"],
    seller: "Spacewood",
    warranty: "1 Year",
  },
  // Books
  {
    name: "The Psychology of Money by Morgan Housel",
    brand: "Jaico Publishing",
    category: "Books",
    price: 299,
    originalPrice: 450,
    discount: 34,
    stock: 350,
    rating: 4.7,
    numReviews: 31000,
    badge: "Best Seller",
    isFeatured: true,
    description: "The Psychology of Money — timeless lessons on wealth, greed, and happiness.",
    highlights: ["Paperback", "English", "256 Pages"],
    image: "/images/products/psychology-money.jpg",
    images: ["/images/products/psychology-money.jpg"],
    tags: ["books", "finance", "psychology"],
    seller: "Jaico Publishing",
    warranty: "",
  },
  {
    name: "Start With Why by Simon Sinek",
    brand: "Penguin",
    category: "Books",
    price: 349,
    originalPrice: 499,
    discount: 30,
    stock: 280,
    rating: 4.6,
    numReviews: 22000,
    badge: "Popular",
    isFeatured: false,
    description: "Start With Why by Simon Sinek — how great leaders inspire everyone to take action.",
    highlights: ["Paperback", "English", "256 Pages"],
    image: "/images/products/start-with-why.jpg",
    images: ["/images/products/start-with-why.jpg"],
    tags: ["books", "leadership", "self help"],
    seller: "Penguin Books",
    warranty: "",
  },
  {
    name: "Think and Grow Rich by Napoleon Hill",
    brand: "Fingerprint Publishing",
    category: "Books",
    price: 199,
    originalPrice: 350,
    discount: 43,
    stock: 420,
    rating: 4.6,
    numReviews: 27000,
    badge: "Classic",
    isFeatured: false,
    description: "Think and Grow Rich — the all-time classic on success and personal achievement.",
    highlights: ["Paperback", "English", "320 Pages"],
    image: "/images/products/think-grow-rich.jpg",
    images: ["/images/products/think-grow-rich.jpg"],
    tags: ["books", "success", "self help"],
    seller: "Fingerprint Publishing",
    warranty: "",
  },
  // Electronics
  {
    name: "Apple MacBook Air M2 8GB 256GB",
    brand: "Apple",
    category: "Electronics",
    price: 99900,
    originalPrice: 114900,
    discount: 13,
    stock: 30,
    rating: 4.8,
    numReviews: 6200,
    badge: "Premium",
    isFeatured: true,
    description: "Apple MacBook Air with M2 chip, 8GB RAM and 256GB SSD for blazing performance.",
    highlights: ["M2 Chip", "8GB RAM", "256GB SSD"],
    image: "/images/products/macbook.jpg",
    images: ["/images/products/macbook.jpg"],
    tags: ["apple", "macbook", "laptop"],
    seller: "Apple Store",
    warranty: "1 Year",
  },
  {
    name: "JBL Flip 6 Portable Bluetooth Speaker",
    brand: "JBL",
    category: "Electronics",
    price: 1999,
    originalPrice: 2999,
    discount: 29,
    stock: 110,
    rating: 4.5,
    numReviews: 8900,
    badge: "Top Rated",
    isFeatured: true,
    description: "JBL Flip 6 portable waterproof Bluetooth speaker with 12 hours playtime.",
    highlights: ["IP67 Waterproof", "12Hr Playtime", "PartyBoost"],
    image: "/images/products/speaker.jpg",
    images: ["/images/products/speaker.jpg"],
    tags: ["jbl", "speaker", "bluetooth"],
    seller: "JBL India",
    warranty: "1 Year",
  },
  {
    name: "SanDisk 128GB USB 3.0 Pen Drive",
    brand: "SanDisk",
    category: "Electronics",
    price: 699,
    originalPrice: 999,
    discount: 30,
    stock: 400,
    rating: 4.4,
    numReviews: 24000,
    badge: "Best Seller",
    isFeatured: false,
    description: "SanDisk 128GB USB 3.0 pen drive with high-speed data transfer up to 130MB/s.",
    highlights: ["128GB Storage", "USB 3.0", "130MB/s Speed"],
    image: "/images/products/pendrive.jpg",
    images: ["/images/products/pendrive.jpg"],
    tags: ["sandisk", "pendrive", "storage"],
    seller: "SanDisk India",
    warranty: "5 Years",
  },
  {
    name: "Logitech M235 Wireless Mouse",
    brand: "Logitech",
    category: "Electronics",
    price: 999,
    originalPrice: 1495,
    discount: 33,
    stock: 220,
    rating: 4.3,
    numReviews: 16000,
    badge: "Popular",
    isFeatured: false,
    description: "Logitech M235 wireless mouse with 12-month battery life and smooth tracking.",
    highlights: ["Wireless 2.4GHz", "12 Month Battery", "Plug & Play"],
    image: "/images/products/mouse.jpg",
    images: ["/images/products/mouse.jpg"],
    tags: ["logitech", "mouse", "wireless"],
    seller: "Logitech India",
    warranty: "3 Years",
  },
  {
    name: "Realme 4K Smart TV Stick",
    brand: "Realme",
    category: "Electronics",
    price: 1299,
    originalPrice: 2999,
    discount: 30,
    stock: 180,
    rating: 4.1,
    numReviews: 7300,
    badge: "Value Pick",
    isFeatured: false,
    description: "Realme 4K Smart TV Stick with Google TV, Chromecast and voice remote.",
    highlights: ["4K Streaming", "Google TV", "Voice Remote"],
    image: "/images/products/realme-tvstick.jpg",
    images: ["/images/products/realme-tvstick.jpg"],
    tags: ["realme", "tv stick", "streaming"],
    seller: "Realme India",
    warranty: "1 Year",
  },
  {
    name: "boAt Airdopes 141 TWS Earbuds",
    brand: "boAt",
    category: "Electronics",
    price: 999,
    originalPrice: 2990,
    discount: 67,
    stock: 350,
    rating: 4.1,
    numReviews: 41000,
    badge: "Best Seller",
    isFeatured: true,
    description: "boAt Airdopes 141 TWS earbuds with 42 hours total playback and BEAST mode.",
    highlights: ["42Hr Total Playback", "BEAST Mode", "IPX4 Water Resistant"],
    image: "/images/products/earbuds.jpg",
    images: ["/images/products/earbuds.jpg"],
    tags: ["boat", "earbuds", "tws"],
    seller: "boAt Official",
    warranty: "1 Year",
  },
  // Fashion
  {
    name: "Raymond Men's Formal Shirt",
    brand: "Raymond",
    category: "Fashion",
    price: 1299,
    originalPrice: 2199,
    discount: 41,
    stock: 160,
    rating: 4.3,
    numReviews: 8400,
    badge: "Popular",
    isFeatured: false,
    description: "Raymond men's slim fit formal shirt in premium cotton blend fabric.",
    highlights: ["Slim Fit", "Cotton Blend", "Wrinkle Resistant"],
    image: "/images/products/shirt.jpg",
    images: ["/images/products/shirt.jpg"],
    tags: ["raymond", "shirt", "formal"],
    seller: "Raymond Store",
    warranty: "",
  },
  {
    name: "Baggit Women's Handbag",
    brand: "Baggit",
    category: "Fashion",
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    stock: 90,
    rating: 4.2,
    numReviews: 5600,
    badge: "Trending",
    isFeatured: false,
    description: "Baggit women's handbag in vegan leather with multiple compartments.",
    highlights: ["Vegan Leather", "Multiple Compartments", "Zip Closure"],
    image: "/images/products/handbag.jpg",
    images: ["/images/products/handbag.jpg"],
    tags: ["baggit", "handbag", "fashion"],
    seller: "Baggit India",
    warranty: "",
  },
  {
    name: "Titan Raga Women's Watch",
    brand: "Titan",
    category: "Fashion",
    price: 4995,
    originalPrice: 6995,
    discount: 29,
    stock: 70,
    rating: 4.5,
    numReviews: 6100,
    badge: "Top Rated",
    isFeatured: true,
    description: "Titan Raga women's analog watch with rose gold case and leather strap.",
    highlights: ["Rose Gold Case", "Leather Strap", "Water Resistant"],
    image: "/images/products/watch.jpg",
    images: ["/images/products/watch.jpg"],
    tags: ["titan", "watch", "women"],
    seller: "Titan Store",
    warranty: "2 Years",
  },
  {
    name: "Wildcraft Men's Running Shoes",
    brand: "Wildcraft",
    category: "Fashion",
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    stock: 140,
    rating: 4.1,
    numReviews: 7200,
    badge: "Value Pick",
    isFeatured: false,
    description: "Wildcraft men's lightweight running shoes with cushioned sole and mesh upper.",
    highlights: ["Mesh Upper", "Cushioned Sole", "Lightweight"],
    image: "/images/products/running-shoes.jpg",
    images: ["/images/products/running-shoes.jpg"],
    tags: ["wildcraft", "shoes", "running"],
    seller: "Wildcraft India",
    warranty: "",
  },
  {
    name: "Peter England Men's Leather Belt",
    brand: "Peter England",
    category: "Fashion",
    price: 599,
    originalPrice: 999,
    discount: 40,
    stock: 200,
    rating: 4.2,
    numReviews: 9300,
    badge: "Popular",
    isFeatured: false,
    description: "Peter England men's genuine leather belt with pin buckle closure.",
    highlights: ["Genuine Leather", "Pin Buckle", "Reversible"],
    image: "/images/products/belt.jpg",
    images: ["/images/products/belt.jpg"],
    tags: ["peter england", "belt", "fashion"],
    seller: "Peter England",
    warranty: "",
  },
  // Home & Furniture
  {
    name: "Nilkamal Bookshelf 4 Shelf",
    brand: "Nilkamal",
    category: "Home & Furniture",
    price: 3999,
    originalPrice: 5999,
    discount: 33,
    stock: 55,
    rating: 4.1,
    numReviews: 2900,
    badge: "Popular",
    isFeatured: false,
    description: "Nilkamal 4-shelf bookshelf in engineered wood for home and office use.",
    highlights: ["4 Shelves", "Engineered Wood", "Easy Assembly"],
    image: "/images/products/bookshelf.jpg",
    images: ["/images/products/bookshelf.jpg"],
    tags: ["nilkamal", "bookshelf", "furniture"],
    seller: "Nilkamal Furniture",
    warranty: "1 Year",
  },
  {
    name: "Hometown 6 Seater Dining Table Set",
    brand: "Hometown",
    category: "Home & Furniture",
    price: 2999,
    originalPrice: 4999,
    discount: 30,
    stock: 12,
    rating: 4.3,
    numReviews: 1800,
    badge: "Premium",
    isFeatured: true,
    description: "Hometown 6 seater dining table set in solid sheesham wood with cushioned chairs.",
    highlights: ["Solid Sheesham Wood", "6 Chairs", "Cushioned Seats"],
    image: "/images/products/dining-table.webp",
    images: ["/images/products/dining-table.webp"],
    tags: ["dining table", "hometown", "furniture"],
    seller: "Hometown",
    warranty: "1 Year",
  },
  // Appliances
  {
    name: "Bajaj Majesty 1000W Electric Kettle",
    brand: "Bajaj",
    category: "Appliances",
    price: 699,
    originalPrice: 999,
    discount: 30,
    stock: 200,
    rating: 4.2,
    numReviews: 13500,
    badge: "Value Pick",
    isFeatured: false,
    description: "Bajaj Majesty 1L electric kettle with auto shut-off and boil-dry protection.",
    highlights: ["1L Capacity", "Auto Shut-Off", "1000W"],
    image: "/images/products/kettle.jpg",
    images: ["/images/products/kettle.jpg"],
    tags: ["bajaj", "kettle", "appliance"],
    seller: "Bajaj Electricals",
    warranty: "1 Year",
  },
  {
    name: "Philips HD9252 Air Fryer 1400W",
    brand: "Philips",
    category: "Appliances",
    price: 7995,
    originalPrice: 11995,
    discount: 33,
    stock: 65,
    rating: 4.5,
    numReviews: 9800,
    badge: "Top Rated",
    isFeatured: true,
    description: "Philips HD9252 air fryer with Rapid Air technology for healthy oil-free cooking.",
    highlights: ["1400W", "Rapid Air Tech", "4.1L Capacity"],
    image: "/images/products/air-fryer.jpg",
    images: ["/images/products/air-fryer.jpg"],
    tags: ["philips", "air fryer", "appliance"],
    seller: "Philips India",
    warranty: "2 Years",
  },
  {
    name: "AO Smith 15L Water Heater",
    brand: "AO Smith",
    category: "Appliances",
    price: 8490,
    originalPrice: 11990,
    discount: 29,
    stock: 45,
    rating: 4.4,
    numReviews: 5200,
    badge: "Popular",
    isFeatured: false,
    description: "AO Smith 15L storage water heater with Blue Diamond glass-lined tank.",
    highlights: ["15L Capacity", "Blue Diamond Tank", "5 Star Rating"],
    image: "/images/products/water-heater.jpg",
    images: ["/images/products/water-heater.jpg"],
    tags: ["ao smith", "water heater", "appliance"],
    seller: "AO Smith India",
    warranty: "7 Years",
  },
  // Beauty
  {
    name: "Minimalist 10% Niacinamide Serum 30ml",
    brand: "Minimalist",
    category: "Beauty",
    price: 599,
    originalPrice: 799,
    discount: 25,
    stock: 280,
    rating: 4.5,
    numReviews: 23000,
    badge: "Top Rated",
    isFeatured: true,
    description: "Minimalist 10% Niacinamide serum for pore reduction and oil control.",
    highlights: ["10% Niacinamide", "Pore Reduction", "Oil Control"],
    image: "/images/products/serum.jpg",
    images: ["/images/products/serum.jpg"],
    tags: ["minimalist", "serum", "beauty"],
    seller: "Minimalist",
    warranty: "",
  },
  {
    name: "Dove Shampoo Intense Repair 650ml",
    brand: "Dove",
    category: "Beauty",
    price: 349,
    originalPrice: 499,
    discount: 30,
    stock: 350,
    rating: 4.3,
    numReviews: 31000,
    badge: "Best Seller",
    isFeatured: false,
    description: "Dove Intense Repair shampoo with Keratin Actives for damaged hair repair.",
    highlights: ["Keratin Actives", "650ml", "Damage Repair"],
    image: "/images/products/shampoo.jpg",
    images: ["/images/products/shampoo.jpg"],
    tags: ["dove", "shampoo", "beauty"],
    seller: "HUL",
    warranty: "",
  },
  // Sports
  {
    name: "Cosco Cricket Bat Kashmir Willow",
    brand: "Cosco",
    category: "Sports",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    stock: 120,
    rating: 4.1,
    numReviews: 5400,
    badge: "Popular",
    isFeatured: false,
    description: "Cosco Kashmir willow cricket bat for practice and club level matches.",
    highlights: ["Kashmir Willow", "Full Size", "Grip Included"],
    image: "/images/products/cricket-bat.jpg",
    images: ["/images/products/cricket-bat.jpg"],
    tags: ["cosco", "cricket", "sports"],
    seller: "Cosco Sports",
    warranty: "",
  },
  {
    name: "Boldfit Yoga Mat 6mm Anti-Slip",
    brand: "Boldfit",
    category: "Sports",
    price: 499,
    originalPrice: 799,
    discount: 38,
    stock: 250,
    rating: 4.3,
    numReviews: 14200,
    badge: "Best Seller",
    isFeatured: false,
    description: "Boldfit 6mm anti-slip yoga mat with carrying strap for home and gym workouts.",
    highlights: ["6mm Thickness", "Anti-Slip", "Carrying Strap"],
    image: "/images/products/yoga-mat.jpg",
    images: ["/images/products/yoga-mat.jpg"],
    tags: ["boldfit", "yoga mat", "sports"],
    seller: "Boldfit",
    warranty: "",
  },
  // Grocery
  {
    name: "Surf Excel Easy Wash Detergent 3kg",
    brand: "Surf Excel",
    category: "Grocery",
    price: 349,
    originalPrice: 420,
    discount: 17,
    stock: 600,
    rating: 4.5,
    numReviews: 38000,
    badge: "Best Seller",
    isFeatured: false,
    description: "Surf Excel Easy Wash detergent powder 3kg for tough stain removal.",
    highlights: ["3kg Pack", "Tough Stain Removal", "Easy Rinse"],
    image: "/images/products/surf-excel.jpg",
    images: ["/images/products/surf-excel.jpg"],
    tags: ["surf excel", "detergent", "grocery"],
    seller: "HUL",
    warranty: "",
  },
  {
    name: "Amul Butter 500g",
    brand: "Amul",
    category: "Grocery",
    price: 275,
    originalPrice: 300,
    discount: 8,
    stock: 800,
    rating: 4.7,
    numReviews: 47000,
    badge: "Daily Essential",
    isFeatured: false,
    description: "Amul pasteurized butter 500g made from fresh cream, rich in taste.",
    highlights: ["500g Pack", "Pasteurized", "Rich Taste"],
    image: "/images/products/amul-butter.jpg",
    images: ["/images/products/amul-butter.jpg"],
    tags: ["amul", "butter", "grocery"],
    seller: "Amul",
    warranty: "",
  },
  {
    name: "Cadbury Dairy Milk Chocolate 200g",
    brand: "Cadbury",
    category: "Grocery",
    price: 199,
    originalPrice: 240,
    discount: 17,
    stock: 700,
    rating: 4.7,
    numReviews: 55000,
    badge: "Loved by All",
    isFeatured: true,
    description: "Cadbury Dairy Milk chocolate 200g with rich creamy milk chocolate taste.",
    highlights: ["200g Pack", "Milk Chocolate", "No Artificial Colours"],
    image: "/images/products/chocolate.jpg",
    images: ["/images/products/chocolate.jpg"],
    tags: ["cadbury", "chocolate", "grocery"],
    seller: "Mondelez India",
    warranty: "",
  },
  // Toys
  {
    name: "Fisher-Price Baby Ride-On Car",
    brand: "Fisher-Price",
    category: "Toys",
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    stock: 80,
    rating: 4.4,
    numReviews: 4300,
    badge: "Popular",
    isFeatured: false,
    description: "Fisher-Price baby ride-on car with push handle and interactive dashboard.",
    highlights: ["Push Handle", "Interactive Dashboard", "Age 1-3"],
    image: "/images/products/ride-on-car.jpg",
    images: ["/images/products/ride-on-car.jpg"],
    tags: ["fisher price", "ride on", "toys"],
    seller: "Mattel India",
    warranty: "",
  },
  {
    name: "Webby Remote Control Racing Car",
    brand: "Webby",
    category: "Toys",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    stock: 130,
    rating: 4.2,
    numReviews: 6700,
    badge: "Trending",
    isFeatured: false,
    description: "Webby high-speed remote control racing car with 2.4GHz controller.",
    highlights: ["2.4GHz Remote", "High Speed", "Age 6+"],
    image: "/images/products/rc-car.jpg",
    images: ["/images/products/rc-car.jpg"],
    tags: ["webby", "rc car", "toys"],
    seller: "Webby Toys",
    warranty: "",
  },
  // Fashion - remaining
  {
    name: "W Women's Floral Dress",
    brand: "W",
    category: "Fashion",
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    stock: 120,
    rating: 4.3,
    numReviews: 7100,
    badge: "Trending",
    isFeatured: false,
    description: "W women's floral printed dress in breathable cotton fabric for casual wear.",
    highlights: ["100% Cotton", "Floral Print", "Regular Fit"],
    image: "/images/products/dress.jpg",
    images: ["/images/products/dress.jpg"],
    tags: ["w", "dress", "fashion"],
    seller: "W Fashion",
    warranty: "",
  },
  {
    name: "Nykaa Sunglasses UV400 Protection",
    brand: "Nykaa",
    category: "Fashion",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    stock: 180,
    rating: 4.1,
    numReviews: 4800,
    badge: "Popular",
    isFeatured: false,
    description: "Nykaa UV400 sunglasses with polarized lenses and lightweight frame.",
    highlights: ["UV400 Protection", "Polarized Lenses", "Lightweight Frame"],
    image: "/images/products/sunglasses.jpg",
    images: ["/images/products/sunglasses.jpg"],
    tags: ["sunglasses", "nykaa", "fashion"],
    seller: "Nykaa Fashion",
    warranty: "",
  },
  {
    name: "Baggit Men's Leather Wallet",
    brand: "Baggit",
    category: "Fashion",
    price: 699,
    originalPrice: 1199,
    discount: 42,
    stock: 200,
    rating: 4.2,
    numReviews: 6300,
    badge: "Popular",
    isFeatured: false,
    description: "Baggit men's bi-fold wallet in vegan leather with multiple card slots.",
    highlights: ["Vegan Leather", "Multiple Card Slots", "Bi-Fold"],
    image: "/images/products/wallet.jpg",
    images: ["/images/products/wallet.jpg"],
    tags: ["baggit", "wallet", "fashion"],
    seller: "Baggit India",
    warranty: "",
  },
  {
    name: "Mochi Women's Block Heel Sandals",
    brand: "Mochi",
    category: "Fashion",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    stock: 110,
    rating: 4.2,
    numReviews: 5200,
    badge: "Trending",
    isFeatured: false,
    description: "Mochi women's block heel sandals with cushioned footbed and ankle strap.",
    highlights: ["Block Heel", "Cushioned Footbed", "Ankle Strap"],
    image: "/images/products/heels.jpg",
    images: ["/images/products/heels.jpg"],
    tags: ["mochi", "heels", "fashion"],
    seller: "Mochi Shoes",
    warranty: "",
  },
  {
    name: "Fabindia Cotton Saree",
    brand: "Fabindia",
    category: "Fashion",
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    stock: 80,
    rating: 4.4,
    numReviews: 3900,
    badge: "Ethnic Wear",
    isFeatured: true,
    description: "Fabindia handwoven cotton saree with zari border and blouse piece.",
    highlights: ["Handwoven Cotton", "Zari Border", "Blouse Piece Included"],
    image: "/images/products/saree.jpg",
    images: ["/images/products/saree.jpg"],
    tags: ["fabindia", "saree", "ethnic"],
    seller: "Fabindia",
    warranty: "",
  },
  {
    name: "Nike Men's Sports Shoes",
    brand: "Nike",
    category: "Fashion",
    price: 1999,
    originalPrice: 4999,
    discount: 33,
    stock: 130,
    rating: 4.4,
    numReviews: 11200,
    badge: "Top Rated",
    isFeatured: true,
    description: "Nike men's lightweight sports shoes with mesh upper and foam cushioning.",
    highlights: ["Mesh Upper", "Foam Cushioning", "Rubber Outsole"],
    image: "/images/products/nike-shoes.jpg",
    images: ["/images/products/nike-shoes.jpg"],
    tags: ["nike", "shoes", "sports"],
    seller: "Nike India",
    warranty: "",
  },
  // Home & Furniture - remaining
  {
    name: "Durian Coffee Table Solid Wood",
    brand: "Durian",
    category: "Home & Furniture",
    price: 8999,
    originalPrice: 12999,
    discount: 31,
    stock: 30,
    rating: 4.3,
    numReviews: 2100,
    badge: "Popular",
    isFeatured: false,
    description: "Durian solid wood coffee table with lower shelf for living room storage.",
    highlights: ["Solid Wood", "Lower Shelf", "Easy Assembly"],
    image: "/images/products/coffee-table.jpg",
    images: ["/images/products/coffee-table.jpg"],
    tags: ["durian", "coffee table", "furniture"],
    seller: "Durian Furniture",
    warranty: "1 Year",
  },
  // Appliances - remaining
  {
    name: "Kent RO Water Purifier 8L",
    brand: "Kent",
    category: "Appliances",
    price: 14999,
    originalPrice: 19999,
    discount: 25,
    stock: 40,
    rating: 4.4,
    numReviews: 12000,
    badge: "Best Seller",
    isFeatured: true,
    description: "Kent Grand Plus RO+UV+UF water purifier with 8L storage and TDS controller.",
    highlights: ["RO+UV+UF", "8L Storage", "TDS Controller"],
    image: "/images/products/ro-purifier.jpg",
    images: ["/images/products/ro-purifier.jpg"],
    tags: ["kent", "water purifier", "appliance"],
    seller: "Kent RO",
    warranty: "1 Year",
  },
  // Beauty - remaining
  {
    name: "Lakme 9 to 5 Makeup Kit",
    brand: "Lakme",
    category: "Beauty",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    stock: 150,
    rating: 4.3,
    numReviews: 9800,
    badge: "Popular",
    isFeatured: false,
    description: "Lakme 9 to 5 makeup kit with eyeshadow, blush, highlighter and brush set.",
    highlights: ["Eyeshadow Palette", "Blush & Highlighter", "Brush Set"],
    image: "/images/products/makeup-kit.jpg",
    images: ["/images/products/makeup-kit.jpg"],
    tags: ["lakme", "makeup", "beauty"],
    seller: "Lakme Beauty",
    warranty: "",
  },
  {
    name: "Nivea Body Lotion 400ml",
    brand: "Nivea",
    category: "Beauty",
    price: 299,
    originalPrice: 425,
    discount: 30,
    stock: 350,
    rating: 4.4,
    numReviews: 26000,
    badge: "Best Seller",
    isFeatured: false,
    description: "Nivea Soft Light Moisturiser body lotion 400ml with Vitamin E and Jojoba oil.",
    highlights: ["Vitamin E", "Jojoba Oil", "400ml"],
    image: "/images/products/body-lotion.jpg",
    images: ["/images/products/body-lotion.jpg"],
    tags: ["nivea", "body lotion", "beauty"],
    seller: "Nivea India",
    warranty: "",
  },
  {
    name: "Plum Goodness Night Gel 50ml",
    brand: "Plum",
    category: "Beauty",
    price: 449,
    originalPrice: 649,
    discount: 31,
    stock: 200,
    rating: 4.3,
    numReviews: 11500,
    badge: "Trending",
    isFeatured: false,
    description: "Plum Goodness E-Luminence night gel with Vitamin E for overnight skin repair.",
    highlights: ["Vitamin E", "Overnight Repair", "Vegan Formula"],
    image: "/images/products/night-gel.jpg",
    images: ["/images/products/night-gel.jpg"],
    tags: ["plum", "night gel", "beauty"],
    seller: "Plum Goodness",
    warranty: "",
  },
  // Sports - remaining
  {
    name: "Decathlon Running Shoes",
    brand: "Decathlon",
    category: "Sports",
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    stock: 180,
    rating: 4.3,
    numReviews: 18000,
    badge: "Value Pick",
    isFeatured: false,
    description: "Decathlon Kiprun lightweight running shoes with cushioned midsole.",
    highlights: ["Lightweight", "Cushioned Midsole", "Breathable Upper"],
    image: "/images/products/running-shoes.jpg",
    images: ["/images/products/running-shoes.jpg"],
    tags: ["decathlon", "running shoes", "sports"],
    seller: "Decathlon India",
    warranty: "",
  },
  // Grocery - remaining
  {
    name: "Red Label Natural Care Tea 500g",
    brand: "Brooke Bond",
    category: "Grocery",
    price: 219,
    originalPrice: 260,
    discount: 16,
    stock: 650,
    rating: 4.4,
    numReviews: 29000,
    badge: "Popular",
    isFeatured: false,
    description: "Brooke Bond Red Label Natural Care tea with 5 Ayurvedic ingredients.",
    highlights: ["5 Ayurvedic Ingredients", "500g Pack", "Natural Care"],
    image: "/images/products/red-label-tea.jpg",
    images: ["/images/products/red-label-tea.jpg"],
    tags: ["red label", "tea", "grocery"],
    seller: "HUL",
    warranty: "",
  },
  // Toys - remaining
  {
    name: "Funskool Doctor Play Set",
    brand: "Funskool",
    category: "Toys",
    price: 599,
    originalPrice: 899,
    discount: 33,
    stock: 160,
    rating: 4.3,
    numReviews: 5100,
    badge: "Popular",
    isFeatured: false,
    description: "Funskool doctor play set with 12 medical accessories for pretend play.",
    highlights: ["12 Accessories", "Pretend Play", "Age 3+"],
    image: "/images/products/doctor-playset.jpg",
    images: ["/images/products/doctor-playset.jpg"],
    tags: ["funskool", "doctor set", "toys"],
    seller: "Funskool India",
    warranty: "",
  },
  {
    name: "Mega Bloks Building Blocks 80 Pieces",
    brand: "Mega Bloks",
    category: "Toys",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    stock: 140,
    rating: 4.4,
    numReviews: 6800,
    badge: "Top Rated",
    isFeatured: false,
    description: "Mega Bloks 80-piece building blocks set for creative construction play.",
    highlights: ["80 Pieces", "Large Blocks", "Age 1+"],
    image: "/images/products/building-blocks.jpg",
    images: ["/images/products/building-blocks.jpg"],
    tags: ["mega bloks", "building blocks", "toys"],
    seller: "Mattel India",
    warranty: "",
  },
];


async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Clear all collections
    await Promise.all([
      User.deleteMany(),
      Product.deleteMany(),
      Category.deleteMany(),
      Order.deleteMany(),
    ]);
    console.log("🗑️  Cleared existing data");

    // Seed categories
    await Category.insertMany(categories);
    console.log(`✅ Seeded ${categories.length} categories`);

    // Seed products
    await Product.insertMany(products);
    console.log(`✅ Seeded ${products.length} products`);

    // Seed users (plain passwords — model's pre-save hook will hash them)
    await User.create([
      {
        name: "Gautam Admin",
        email: "gautam2028@gmail.com",
        password: "gautam@2028",
        role: "admin",
        phone: "9999999999",
      },
      {
        name: "Test User",
        email: "user@flipkart.com",
        password: "user123",
        role: "user",
        phone: "8888888888",
      },
    ]);
    console.log("✅ Seeded 2 users");

    console.log("\n🎉 Database seeded successfully!\n");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log("👤 Admin  → gautam2028@gmail.com / gautam@2028");
    console.log("👤 User   → user@flipkart.com    / user123");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
    process.exit(0);
  } catch (err) {
    console.error("❌ Seeding failed:", err.message);
    process.exit(1);
  }
}

seed();
